// export const Config = {
//   baseUrl: "http://localhost:8000",
//   SignUPUrl: "http://localhost:8000/api/user/signup",
//   LOGINUrl: "http://localhost:8000/api/user/login",
//   FORGOTPASSWORDUrl: "http://localhost:8000/api/user/forgot-password",
//   GoogleClientId: "748627875694-hqpvo0akdcvtgjpvqluoap2dm3bafbia.apps.googleusercontent.com",
//   GoogleSignUpUrl: "http://localhost:8000/api/user/googleLogin",
//   LogoutUrl: "http://localhost:8000/api/user/logout",
//   ContactUrl: "http://localhost:8000/api/contacts/addcontact",
//   GETDATAUrl: "http://localhost:8000/api/user/get-data",
//   CHECKAuthUrl: "http://localhost:8000/api/user/auth-check",
//   DELETECONTACTUrl: "http://localhost:8000/api/contacts/delete-contact",
//   EMERGENCYUrl: "http://localhost:8000/api/contacts/emergency",
//   ADDREVIEWUrl: "http://localhost:8000/api/reviews/addreview",
//   GETREVIEWSUrl: "http://localhost:8000/api/reviews/allreviews",
//   DELETEREVIEWUrl: "http://localhost:8000/api/reviews/delete-review",
//   ADDPROFILEPHOTO: "http://localhost:8000/api/profile/add-photo",
//   UPDATEUSERNAME: "http://localhost:8000/api/profile/update-name",
//   UPDATEEMAIL: "http://localhost:8000/api/profile/update-email",
//   UPDATEPASSWORD: "http://localhost:8000/api/profile/update-password",
//   EMERGENCYVIDEOUrl: "http://localhost:8000/api/contacts/emergency/video",
//   UPDATEHOMEUrl: "http://localhost:8000/api/user/update-home",
// }


const BASE_URL = import.meta.env.VITE_BACKEND_URL;

export const Config = {
  baseUrl: BASE_URL,
  SignUPUrl: `${BASE_URL}/api/user/signup`,
  LOGINUrl: `${BASE_URL}/api/user/login`,
  FORGOTPASSWORDUrl: `${BASE_URL}/api/user/forgot-password`,
  GoogleClientId: import.meta.env.VITE_GOOGLE_CLIENT_ID,
  GoogleSignUpUrl: `${BASE_URL}/api/user/googleLogin`,
  LogoutUrl: `${BASE_URL}/api/user/logout`,
  ContactUrl: `${BASE_URL}/api/contacts/addcontact`,
  GETDATAUrl: `${BASE_URL}/api/user/get-data`,
  CHECKAuthUrl: `${BASE_URL}/api/user/auth-check`,
  DELETECONTACTUrl: `${BASE_URL}/api/contacts/delete-contact`,
  EMERGENCYUrl: `${BASE_URL}/api/contacts/emergency`,
  ADDREVIEWUrl: `${BASE_URL}/api/reviews/addreview`,
  GETREVIEWSUrl: `${BASE_URL}/api/reviews/allreviews`,
  DELETEREVIEWUrl: `${BASE_URL}/api/reviews/delete-review`,
  ADDPROFILEPHOTO: `${BASE_URL}/api/profile/add-photo`,
  UPDATEUSERNAME: `${BASE_URL}/api/profile/update-name`,
  UPDATEEMAIL: `${BASE_URL}/api/profile/update-email`,
  UPDATEPASSWORD: `${BASE_URL}/api/profile/update-password`,
  EMERGENCYVIDEOUrl: `${BASE_URL}/api/contacts/emergency/video`,
  UPDATEHOMEUrl: `${BASE_URL}/api/user/update-home`,
};